# Generated by Django 3.2.9 on 2021-12-06 08:53

import django.core.validators
from django.db import migrations, models
import teams.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField(validators=[django.core.validators.MinValueValidator(1850), teams.models.max_value_current_year], verbose_name='year')),
                ('stadium', models.CharField(max_length=200)),
                ('capacity', models.IntegerField()),
                ('owner', models.CharField(max_length=150)),
                ('chairman', models.CharField(max_length=150)),
            ],
        ),
    ]
