# Generated by Django 3.2.9 on 2021-12-05 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
                ('region', models.CharField(max_length=150)),
                ('organising_body', models.CharField(max_length=150)),
                ('date_founded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
