# Generated by Django 3.2.9 on 2021-12-06 05:43

import cup.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cup',
            name='date_founded',
        ),
        migrations.AddField(
            model_name='cup',
            name='year',
            field=models.IntegerField(default=2000, validators=[django.core.validators.MinValueValidator(1850), cup.models.max_value_current_year], verbose_name='year'),
            preserve_default=False,
        ),
    ]
