# Generated by Django 3.2.9 on 2021-12-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_region'),
        ('cup', '0002_auto_20211206_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cup',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.region'),
        ),
    ]
