# Generated by Django 3.2.9 on 2021-12-05 19:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('organising_body', models.CharField(max_length=150)),
                ('date_founded', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.CharField(max_length=100)),
                ('confederation', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('domestic_cup', models.ManyToManyField(blank=True, related_name='domestic_cup', to='cup.Cup')),
                ('international_cup', models.ManyToManyField(blank=True, related_name='international_cup', to='cup.Cup')),
                ('league_cup', models.ManyToManyField(blank=True, related_name='league_cup', to='cup.Cup')),
                ('relegation_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='league.league')),
            ],
        ),
    ]
