# Generated by Django 3.2.9 on 2021-12-06 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='title',
        ),
        migrations.AlterField(
            model_name='competition',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'league'), ('model', 'league')), models.Q(('app_label', 'cup'), ('model', 'cup')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
