# Generated by Django 3.2.9 on 2021-12-08 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_manager_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerreign',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
